# Generated by Django 5.0.1 on 2024-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default=123456, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='password2',
            field=models.CharField(max_length=128),
        ),
    ]
