# Generated by Django 5.0.1 on 2024-03-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_profile_password_profile_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
