# Generated by Django 5.0.1 on 2024-03-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_delete_user_rename_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
