# Generated by Django 5.0.1 on 2024-03-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
