# Generated by Django 5.0.1 on 2024-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_room_host_remove_room_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Pracownik'), ('guest', 'Gość')], default='guest', max_length=20),
        ),
    ]
