# Generated by Django 5.0.1 on 2024-03-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
