# Generated by Django 5.0.3 on 2024-04-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_document_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departament',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('SALES', 'SALES')], default='hr', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Pracownik'), ('guest', 'Gość')], default='guest', max_length=20),
        ),
    ]
