# Generated by Django 5.0.3 on 2024-04-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_profile_departament_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='departament',
            new_name='department',
        ),
    ]
