# Generated by Django 5.0.3 on 2024-04-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_departament_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Manager'), ('employee', 'Pracownik'), ('guest', 'Gość')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(choices=[('IT', 'IT'), ('SALES', 'Sales'), ('HR', 'HR')], default='IT', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('SALES', 'SALES')], default='HR', max_length=100),
        ),
    ]
