# Generated by Django 5.0.3 on 2024-04-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_document_access_remove_document_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='HRDocument',
        ),
        migrations.CreateModel(
            name='ITDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
