# Generated by Django 5.0.3 on 2024-04-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_hrdocument_created_at_hrdocument_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='itdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrdocument_last_edited', to='base.profile'),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='last_replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrdocument_last_replaced', to='base.profile'),
        ),
        migrations.AddField(
            model_name='itdocument',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itdocument_last_edited', to='base.profile'),
        ),
        migrations.AddField(
            model_name='itdocument',
            name='last_replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itdocument_last_replaced', to='base.profile'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesdocument_last_edited', to='base.profile'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='last_replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesdocument_last_replaced', to='base.profile'),
        ),
    ]
