# Generated by Django 5.0.3 on 2024-04-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_hrdocument_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdocument',
            name='last_replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itdocument',
            name='last_replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='last_replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
