# Generated by Django 5.0.4 on 2024-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_financedocument_recipient_hrdocument_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financedocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itdocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logisticsdocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
