# Generated by Django 5.0.4 on 2024-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_financedocument_file_alter_hrdocument_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senddocument',
            name='recipient',
        ),
        migrations.AddField(
            model_name='senddocument',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_documents', to='base.profile'),
        ),
    ]
