# Generated by Django 5.0.4 on 2024-04-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_remove_senddocument_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senddocument',
            name='recipients',
        ),
        migrations.AddField(
            model_name='senddocument',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='base.profile'),
        ),
    ]
