# Generated by Django 5.0.4 on 2024-04-26 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_senddocument_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senddocument',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_documents', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='senddocument',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_single_documents', to='base.profile'),
        ),
    ]
