# Generated by Django 5.0.4 on 2024-05-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_senddocument_recipients_alter_senddocument_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='base.profile'),
        ),
    ]
