# Generated by Django 5.0.4 on 2024-05-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_profile_lockout_time_profile_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senddocument',
            name='public_key',
        ),
    ]
