# Generated by Django 5.0.4 on 2024-05-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_senddocument_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('public_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.publickey')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_keys', to='base.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_keys', to='base.profile')),
            ],
        ),
    ]
